# Copyright 2026 Ryan Alberts
# Licensed under the Apache License, Version 2.0
"""State-by-state Secretary of State / business-formation portal links.

This module is a hand-curated data table. We do NOT scrape state databases —
they vary wildly in format and break often. Instead we surface the canonical
links so the founder can complete the lookup themselves in their browser.

Source: each state's official .gov domain as of repo authoring. URLs that
were uncertain at write time are marked `TODO` in the inline comments — they
point at the state's main SoS page so the founder can navigate from there.

Schema:
  STATE_PORTALS[<2-letter code>] = {
      "name":                       str,
      "sos_business_filings_url":   str | None,
      "business_name_search_url":   str | None,
      "articles_of_organization_url": str | None,
      "annual_report_url":          str | None,
      "registered_agent_info_url":  str | None,
      "filing_fee_articles":        str | None,   # "$300", "$50–$100", etc.
      "annual_fee_approximate":     str | None,
      "notes":                      str | None,   # state-specific quirks
  }

  FEDERAL_PORTALS = { <slug>: <url>, ... }

If you spot a stale URL, fix it here — every Tool and prompt downstream reads
from this single source of truth.
"""
from __future__ import annotations


STATE_PORTALS: dict[str, dict[str, str | None]] = {
    "AL": {
        "name": "Alabama",
        "sos_business_filings_url": "https://www.sos.alabama.gov/business-entities",
        "business_name_search_url": "https://arc-sos.state.al.us/cgi/corpname.mbr/input",
        "articles_of_organization_url": "https://www.sos.alabama.gov/business-entities/forms",
        "annual_report_url": "https://revenue.alabama.gov/business-privilege/",
        "registered_agent_info_url": "https://www.sos.alabama.gov/business-entities",
        "filing_fee_articles": "$200 (state) + $50 (county recording)",
        "annual_fee_approximate": "$100 minimum business privilege tax",
        "notes": "Alabama requires county-level filing in addition to the state. Business privilege tax replaces a traditional annual report.",
    },
    "AK": {
        "name": "Alaska",
        "sos_business_filings_url": "https://www.commerce.alaska.gov/web/cbpl/Corporations.aspx",
        "business_name_search_url": "https://www.commerce.alaska.gov/cbp/main/search/entities",
        "articles_of_organization_url": "https://www.commerce.alaska.gov/web/cbpl/Corporations/Forms.aspx",
        "annual_report_url": "https://www.commerce.alaska.gov/cbp/main",
        "registered_agent_info_url": "https://www.commerce.alaska.gov/web/cbpl/Corporations.aspx",
        "filing_fee_articles": "$250",
        "annual_fee_approximate": "$100 biennial report",
        "notes": "Alaska is filed through the Division of Corporations, Business & Professional Licensing — not a standalone Secretary of State office.",
    },
    "AZ": {
        "name": "Arizona",
        "sos_business_filings_url": "https://azcc.gov/corporations",
        "business_name_search_url": "https://ecorp.azcc.gov/EntitySearch/Index",
        "articles_of_organization_url": "https://azcc.gov/corporations/forms",
        "annual_report_url": "https://azcc.gov/corporations/annual-reports",
        "registered_agent_info_url": "https://azcc.gov/corporations/statutory-agent-info",
        "filing_fee_articles": "$50 (standard) / $85 (expedited)",
        "annual_fee_approximate": "$0 for LLCs (no annual report); $45 for corporations",
        "notes": "Arizona LLCs do NOT file annual reports. AZ also requires newspaper publication of formation in most counties (Maricopa and Pima are exempt).",
    },
    "AR": {
        "name": "Arkansas",
        "sos_business_filings_url": "https://www.sos.arkansas.gov/business-commercial-services-bcs",
        "business_name_search_url": "https://www.sos.arkansas.gov/corps/search_corps.php",
        "articles_of_organization_url": "https://www.sos.arkansas.gov/business-commercial-services-bcs/business-forms",
        "annual_report_url": "https://www.sos.arkansas.gov/business-commercial-services-bcs/franchise-tax",
        "registered_agent_info_url": "https://www.sos.arkansas.gov/business-commercial-services-bcs",
        "filing_fee_articles": "$45 (online) / $50 (paper)",
        "annual_fee_approximate": "$150 franchise tax (LLC minimum)",
        "notes": "Arkansas franchise tax is due May 1 annually.",
    },
    "CA": {
        "name": "California",
        "sos_business_filings_url": "https://www.sos.ca.gov/business-programs/business-entities",
        "business_name_search_url": "https://bizfileonline.sos.ca.gov/search/business",
        "articles_of_organization_url": "https://www.sos.ca.gov/business-programs/business-entities/forms",
        "annual_report_url": "https://www.sos.ca.gov/business-programs/business-entities/statements",
        "registered_agent_info_url": "https://www.sos.ca.gov/business-programs/business-entities/service",
        "filing_fee_articles": "$70 (Articles of Organization)",
        "annual_fee_approximate": "$800 minimum franchise tax + $20 Statement of Information (biennial)",
        "notes": "California's $800 minimum franchise tax applies to ALL LLCs/Corps regardless of revenue — the highest baseline cost of any state. Statement of Information is due within 90 days of formation and biennially thereafter.",
    },
    "CO": {
        "name": "Colorado",
        "sos_business_filings_url": "https://www.sos.state.co.us/pubs/business/main.html",
        "business_name_search_url": "https://www.sos.state.co.us/biz/BusinessEntityCriteriaExt.do",
        "articles_of_organization_url": "https://www.sos.state.co.us/pubs/business/main.html",
        "annual_report_url": "https://www.sos.state.co.us/pubs/business/PeriodicReportsHome.html",
        "registered_agent_info_url": "https://www.sos.state.co.us/pubs/business/FAQs/regAgent.html",
        "filing_fee_articles": "$50",
        "annual_fee_approximate": "$10 periodic report",
        "notes": "Colorado is one of the cheapest states to form and maintain an LLC. Online-only filings.",
    },
    "CT": {
        "name": "Connecticut",
        "sos_business_filings_url": "https://business.ct.gov/",
        "business_name_search_url": "https://service.ct.gov/business/s/onlinebusinesssearch",
        "articles_of_organization_url": "https://business.ct.gov/start",
        "annual_report_url": "https://business.ct.gov/manage/maintain/file-an-annual-report",
        "registered_agent_info_url": "https://business.ct.gov/manage/maintain",
        "filing_fee_articles": "$120",
        "annual_fee_approximate": "$80 annual report",
        "notes": "Connecticut switched to business.ct.gov as the unified business portal in 2020.",
    },
    "DE": {
        "name": "Delaware",
        "sos_business_filings_url": "https://corp.delaware.gov/",
        "business_name_search_url": "https://icis.corp.delaware.gov/Ecorp/EntitySearch/NameSearch.aspx",
        "articles_of_organization_url": "https://corp.delaware.gov/howtoform/",
        "annual_report_url": "https://corp.delaware.gov/paytaxes/",
        "registered_agent_info_url": "https://corp.delaware.gov/agents/",
        "filing_fee_articles": "$110 (Certificate of Formation for LLC) / $89 (Certificate of Incorporation for Corp)",
        "annual_fee_approximate": "$300 LLC franchise tax flat; $175+ corp franchise tax (varies with shares)",
        "notes": "Delaware is the venture-track default for C-Corps because of established case law and the Court of Chancery — but for non-VC bootstrapped LLCs it usually adds cost without benefit. Foreign-LLC registration in your home state is required if you operate elsewhere.",
    },
    "FL": {
        "name": "Florida",
        "sos_business_filings_url": "https://dos.fl.gov/sunbiz/",
        "business_name_search_url": "https://search.sunbiz.org/Inquiry/CorporationSearch/ByName",
        "articles_of_organization_url": "https://dos.fl.gov/sunbiz/forms/limited-liability-company/",
        "annual_report_url": "https://dos.fl.gov/sunbiz/manage-business/annual-report/",
        "registered_agent_info_url": "https://dos.fl.gov/sunbiz/start-business/efile/fl-llc/instructions/",
        "filing_fee_articles": "$125 (LLC) / $70 (Corp)",
        "annual_fee_approximate": "$138.75 LLC annual report",
        "notes": "Florida is popular for asset protection. No state income tax. Annual report due May 1; $400 late fee if missed.",
    },
    "GA": {
        "name": "Georgia",
        "sos_business_filings_url": "https://sos.ga.gov/corporations-division-georgia-secretary-state",
        "business_name_search_url": "https://ecorp.sos.ga.gov/BusinessSearch",
        "articles_of_organization_url": "https://sos.ga.gov/how-to-guide/how-register-llc",
        "annual_report_url": "https://sos.ga.gov/annual-registration",
        "registered_agent_info_url": "https://sos.ga.gov/corporations-division-georgia-secretary-state",
        "filing_fee_articles": "$100 (online)",
        "annual_fee_approximate": "$50 annual registration",
        "notes": "Annual registration due April 1.",
    },
    "HI": {
        "name": "Hawaii",
        "sos_business_filings_url": "https://cca.hawaii.gov/breg/",
        "business_name_search_url": "https://hbe.ehawaii.gov/documents/search.html",
        "articles_of_organization_url": "https://cca.hawaii.gov/breg/registration/dllc/",
        "annual_report_url": "https://cca.hawaii.gov/breg/annual_reports/",
        "registered_agent_info_url": "https://cca.hawaii.gov/breg/",
        "filing_fee_articles": "$50",
        "annual_fee_approximate": "$15 annual report",
        "notes": "Filed through the Department of Commerce and Consumer Affairs (DCCA), not a standalone SoS.",
    },
    "ID": {
        "name": "Idaho",
        "sos_business_filings_url": "https://sos.idaho.gov/business-services/",
        "business_name_search_url": "https://sosbiz.idaho.gov/search/business",
        "articles_of_organization_url": "https://sos.idaho.gov/business-services/business-entities-forms/",
        "annual_report_url": "https://sosbiz.idaho.gov/",
        "registered_agent_info_url": "https://sos.idaho.gov/business-services/",
        "filing_fee_articles": "$100 (online) / $120 (paper)",
        "annual_fee_approximate": "$0 (annual report is free, but must be filed)",
        "notes": "Idaho is one of the few states with no annual report fee — but you still need to file the report.",
    },
    "IL": {
        "name": "Illinois",
        "sos_business_filings_url": "https://www.ilsos.gov/departments/business_services/home.html",
        "business_name_search_url": "https://apps.ilsos.gov/businessentitysearch/",
        "articles_of_organization_url": "https://www.ilsos.gov/departments/business_services/llc.html",
        "annual_report_url": "https://www.ilsos.gov/departments/business_services/annual_reports.html",
        "registered_agent_info_url": "https://www.ilsos.gov/departments/business_services/registered_agent.html",
        "filing_fee_articles": "$150",
        "annual_fee_approximate": "$75 annual report",
        "notes": "Illinois has higher fees than neighboring states but a straightforward online process.",
    },
    "IN": {
        "name": "Indiana",
        "sos_business_filings_url": "https://www.in.gov/sos/business/",
        "business_name_search_url": "https://bsd.sos.in.gov/publicbusinesssearch",
        "articles_of_organization_url": "https://inbiz.in.gov/",
        "annual_report_url": "https://inbiz.in.gov/",
        "registered_agent_info_url": "https://www.in.gov/sos/business/registered-agent/",
        "filing_fee_articles": "$95 (online) / $100 (paper)",
        "annual_fee_approximate": "$31 biennial report",
        "notes": "Indiana files biennially, not annually — half the paperwork of most states.",
    },
    "IA": {
        "name": "Iowa",
        "sos_business_filings_url": "https://sos.iowa.gov/business/",
        "business_name_search_url": "https://sos.iowa.gov/search/business/search.aspx",
        "articles_of_organization_url": "https://sos.iowa.gov/business/forms.html",
        "annual_report_url": "https://sos.iowa.gov/business/biennialreport.html",
        "registered_agent_info_url": "https://sos.iowa.gov/business/",
        "filing_fee_articles": "$50",
        "annual_fee_approximate": "$45 biennial report (online)",
        "notes": "Iowa files biennial reports in odd-numbered years.",
    },
    "KS": {
        "name": "Kansas",
        "sos_business_filings_url": "https://sos.ks.gov/businesses/businesses.html",
        "business_name_search_url": "https://www.sos.ks.gov/eforms/BusinessEntity/Search.aspx",
        "articles_of_organization_url": "https://sos.ks.gov/businesses/business_filing_center.html",
        "annual_report_url": "https://sos.ks.gov/businesses/business_filing_center.html",
        "registered_agent_info_url": "https://sos.ks.gov/businesses/businesses.html",
        "filing_fee_articles": "$160 (online) / $165 (paper)",
        "annual_fee_approximate": "$50 annual report",
        "notes": "Annual report due 15th day of the 4th month after fiscal year end.",
    },
    "KY": {
        "name": "Kentucky",
        "sos_business_filings_url": "https://www.sos.ky.gov/bus/Pages/default.aspx",
        "business_name_search_url": "https://web.sos.ky.gov/ftshow/(S())/default.aspx",
        "articles_of_organization_url": "https://onestop.ky.gov/start/Pages/business-structure.aspx",
        "annual_report_url": "https://www.sos.ky.gov/bus/Pages/annual.aspx",
        "registered_agent_info_url": "https://www.sos.ky.gov/bus/Pages/default.aspx",
        "filing_fee_articles": "$40",
        "annual_fee_approximate": "$15 annual report",
        "notes": "Kentucky is one of the cheapest states overall.",
    },
    "LA": {
        "name": "Louisiana",
        "sos_business_filings_url": "https://www.sos.la.gov/BusinessServices/Pages/default.aspx",
        "business_name_search_url": "https://coraweb.sos.la.gov/CommercialSearch/CommercialSearch.aspx",
        "articles_of_organization_url": "https://www.sos.la.gov/BusinessServices/StartABusiness/Pages/default.aspx",
        "annual_report_url": "https://www.sos.la.gov/BusinessServices/MaintainABusiness/FileAnAnnualReport/Pages/default.aspx",
        "registered_agent_info_url": "https://www.sos.la.gov/BusinessServices/Pages/default.aspx",
        "filing_fee_articles": "$100",
        "annual_fee_approximate": "$35 annual report",
        "notes": "Louisiana operates under civil law (not common law) which affects contract and entity structure — consult a Louisiana attorney.",
    },
    "ME": {
        "name": "Maine",
        "sos_business_filings_url": "https://www.maine.gov/sos/cec/corp/index.html",
        "business_name_search_url": "https://icrs.informe.org/nei-sos-icrs/ICRS",
        "articles_of_organization_url": "https://www.maine.gov/sos/cec/corp/llc.html",
        "annual_report_url": "https://www.maine.gov/sos/cec/corp/annual.html",
        "registered_agent_info_url": "https://www.maine.gov/sos/cec/corp/clerk.html",
        "filing_fee_articles": "$175",
        "annual_fee_approximate": "$85 annual report",
        "notes": "Annual report due June 1.",
    },
    "MD": {
        "name": "Maryland",
        "sos_business_filings_url": "https://dat.maryland.gov/businesses/Pages/default.aspx",
        "business_name_search_url": "https://egov.maryland.gov/BusinessExpress/EntitySearch",
        "articles_of_organization_url": "https://egov.maryland.gov/businessexpress",
        "annual_report_url": "https://dat.maryland.gov/businesses/Pages/Annual-Report-and-Personal-Property-Return.aspx",
        "registered_agent_info_url": "https://dat.maryland.gov/businesses/Pages/Resident-Agent.aspx",
        "filing_fee_articles": "$100 (standard) / $150 (expedited)",
        "annual_fee_approximate": "$300 annual report + personal property tax filing",
        "notes": "Maryland files through the Department of Assessments and Taxation (SDAT). Annual report due April 15.",
    },
    "MA": {
        "name": "Massachusetts",
        "sos_business_filings_url": "https://www.sec.state.ma.us/cor/coridx.htm",
        "business_name_search_url": "https://corp.sec.state.ma.us/corpweb/CorpSearch/CorpSearch.aspx",
        "articles_of_organization_url": "https://www.sec.state.ma.us/cor/corpdf/forms.htm",
        "annual_report_url": "https://www.sec.state.ma.us/cor/corpweb/corweblog.aspx",
        "registered_agent_info_url": "https://www.sec.state.ma.us/cor/coridx.htm",
        "filing_fee_articles": "$500 (LLC) / $275 (Corp)",
        "annual_fee_approximate": "$500 annual report (LLC) / $125 (Corp)",
        "notes": "Massachusetts has unusually high LLC fees ($500 to form, $500 annual). Filed through the Corporations Division of the Secretary of the Commonwealth.",
    },
    "MI": {
        "name": "Michigan",
        "sos_business_filings_url": "https://www.michigan.gov/lara/bureau-list/cscl",
        "business_name_search_url": "https://cofs.lara.state.mi.us/SearchApi/Search/Search",
        "articles_of_organization_url": "https://www.michigan.gov/lara/bureau-list/cscl/forms-publications/business",
        "annual_report_url": "https://www.michigan.gov/lara/bureau-list/cscl/annual-reports",
        "registered_agent_info_url": "https://www.michigan.gov/lara/bureau-list/cscl",
        "filing_fee_articles": "$50",
        "annual_fee_approximate": "$25 annual statement",
        "notes": "Michigan files through LARA (Licensing and Regulatory Affairs), not the Secretary of State.",
    },
    "MN": {
        "name": "Minnesota",
        "sos_business_filings_url": "https://www.sos.state.mn.us/business-liens/",
        "business_name_search_url": "https://mblsportal.sos.state.mn.us/Business/Search",
        "articles_of_organization_url": "https://www.sos.state.mn.us/business-liens/business-forms-fees/",
        "annual_report_url": "https://www.sos.state.mn.us/business-liens/business-help/annual-renewal/",
        "registered_agent_info_url": "https://www.sos.state.mn.us/business-liens/business-help/",
        "filing_fee_articles": "$155 (online) / $135 (paper)",
        "annual_fee_approximate": "$0 (must file annual renewal but no fee)",
        "notes": "Minnesota requires annual renewal but charges no fee — missing the deadline still triggers administrative dissolution.",
    },
    "MS": {
        "name": "Mississippi",
        "sos_business_filings_url": "https://www.sos.ms.gov/business-services",
        "business_name_search_url": "https://corp.sos.ms.gov/corp/portal/c/page/corpbusinessidsearch/portal.aspx",
        "articles_of_organization_url": "https://www.sos.ms.gov/business-services/start-a-business",
        "annual_report_url": "https://www.sos.ms.gov/business-services/annual-report",
        "registered_agent_info_url": "https://www.sos.ms.gov/business-services",
        "filing_fee_articles": "$50",
        "annual_fee_approximate": "$25 annual report (corporations) / $0 (LLCs but must file)",
        "notes": "Mississippi LLC annual reports are free but mandatory.",
    },
    "MO": {
        "name": "Missouri",
        "sos_business_filings_url": "https://www.sos.mo.gov/business",
        "business_name_search_url": "https://bsd.sos.mo.gov/BusinessEntity/BESearch.aspx",
        "articles_of_organization_url": "https://www.sos.mo.gov/business/corporations/startBusiness",
        "annual_report_url": "https://www.sos.mo.gov/business/corporations/annualReport",
        "registered_agent_info_url": "https://www.sos.mo.gov/business/corporations/registeredAgent",
        "filing_fee_articles": "$50 (online) / $105 (paper)",
        "annual_fee_approximate": "$0 for LLCs (no annual report); $45 for corporations",
        "notes": "Missouri LLCs do NOT file annual reports — one of the lowest maintenance burdens.",
    },
    "MT": {
        "name": "Montana",
        "sos_business_filings_url": "https://sosmt.gov/business/",
        "business_name_search_url": "https://biz.sosmt.gov/search/business",
        "articles_of_organization_url": "https://sosmt.gov/business/forms/",
        "annual_report_url": "https://sosmt.gov/business/annual-reports/",
        "registered_agent_info_url": "https://sosmt.gov/business/",
        "filing_fee_articles": "$35",
        "annual_fee_approximate": "$20 annual report",
        "notes": "Montana has no state sales tax. Annual report due April 15.",
    },
    "NE": {
        "name": "Nebraska",
        "sos_business_filings_url": "https://sos.nebraska.gov/business-services",
        "business_name_search_url": "https://www.nebraska.gov/sos/corp/corpsearch.cgi",
        "articles_of_organization_url": "https://sos.nebraska.gov/business-services/limited-liability-companies",
        "annual_report_url": "https://sos.nebraska.gov/business-services/biennial-reports",
        "registered_agent_info_url": "https://sos.nebraska.gov/business-services",
        "filing_fee_articles": "$100",
        "annual_fee_approximate": "$10 biennial report (LLC) / $26+ (Corp, varies)",
        "notes": "Nebraska also requires newspaper publication of formation — typically $40–$200 depending on county.",
    },
    "NV": {
        "name": "Nevada",
        "sos_business_filings_url": "https://www.nvsos.gov/sos/businesses",
        "business_name_search_url": "https://esos.nv.gov/EntitySearch/OnlineEntitySearch",
        "articles_of_organization_url": "https://www.nvsos.gov/sos/businesses/start-a-business",
        "annual_report_url": "https://www.nvsos.gov/sos/businesses/annual-reports",
        "registered_agent_info_url": "https://www.nvsos.gov/sos/businesses/registered-agent",
        "filing_fee_articles": "$425 (Articles + initial list + state business license)",
        "annual_fee_approximate": "$350 (annual list + business license renewal)",
        "notes": "Nevada is marketed for asset protection and privacy, but actual costs are HIGH (~$425 to form, ~$350/year) — often higher than home-state + Delaware foreign-LLC combined.",
    },
    "NH": {
        "name": "New Hampshire",
        "sos_business_filings_url": "https://www.sos.nh.gov/corporations",
        "business_name_search_url": "https://quickstart.sos.nh.gov/online/BusinessInquire",
        "articles_of_organization_url": "https://quickstart.sos.nh.gov/online/Account",
        "annual_report_url": "https://quickstart.sos.nh.gov/online/Account",
        "registered_agent_info_url": "https://www.sos.nh.gov/corporations",
        "filing_fee_articles": "$100",
        "annual_fee_approximate": "$100 annual report",
        "notes": "New Hampshire has no state sales tax and no general income tax (but does tax interest/dividends).",
    },
    "NJ": {
        "name": "New Jersey",
        "sos_business_filings_url": "https://www.nj.gov/treasury/revenue/dcr/programs/business.shtml",
        "business_name_search_url": "https://www.njportal.com/DOR/BusinessNameSearch",
        "articles_of_organization_url": "https://www.njportal.com/dor/businessformation/",
        "annual_report_url": "https://www.njportal.com/DOR/AnnualReports",
        "registered_agent_info_url": "https://www.nj.gov/treasury/revenue/dcr/programs/business.shtml",
        "filing_fee_articles": "$125",
        "annual_fee_approximate": "$75 annual report",
        "notes": "New Jersey files through the Division of Revenue and Enterprise Services (DORES).",
    },
    "NM": {
        "name": "New Mexico",
        "sos_business_filings_url": "https://www.sos.nm.gov/business-services/",
        "business_name_search_url": "https://enterprise.sos.nm.gov/search",
        "articles_of_organization_url": "https://www.sos.nm.gov/business-services/start-a-business/",
        "annual_report_url": "https://www.sos.nm.gov/business-services/maintain-a-business/",
        "registered_agent_info_url": "https://www.sos.nm.gov/business-services/",
        "filing_fee_articles": "$50",
        "annual_fee_approximate": "$0 for LLCs (no annual report); $25 for corporations",
        "notes": "New Mexico LLCs have NO annual report requirement, making it popular for low-maintenance entities. Also offers strong anonymity (no member disclosure on formation).",
    },
    "NY": {
        "name": "New York",
        "sos_business_filings_url": "https://dos.ny.gov/corporations",
        "business_name_search_url": "https://apps.dos.ny.gov/publicInquiry/",
        "articles_of_organization_url": "https://dos.ny.gov/forms/corporations/limited-liability-companies",
        "annual_report_url": "https://dos.ny.gov/corporations/biennial-statement",
        "registered_agent_info_url": "https://dos.ny.gov/corporations",
        "filing_fee_articles": "$200",
        "annual_fee_approximate": "$9 biennial statement + LLC publication ~$1,000–$2,000 in NYC counties",
        "notes": "NY LLCs MUST publish formation notice in two newspapers for 6 weeks — this can cost $1,000–$2,000+ in NYC counties (Manhattan, Brooklyn, Queens). The biggest hidden cost of NY incorporation.",
    },
    "NC": {
        "name": "North Carolina",
        "sos_business_filings_url": "https://www.sosnc.gov/divisions/business_registration",
        "business_name_search_url": "https://www.sosnc.gov/online_services/search/by_title/_Business_Registration",
        "articles_of_organization_url": "https://www.sosnc.gov/divisions/business_registration/forms",
        "annual_report_url": "https://www.sosnc.gov/divisions/business_registration/annual_report",
        "registered_agent_info_url": "https://www.sosnc.gov/divisions/business_registration",
        "filing_fee_articles": "$125",
        "annual_fee_approximate": "$200 annual report (LLC) / $25 (Corp)",
        "notes": "NC has unusually high LLC annual fees ($200 vs. typical $50–$100).",
    },
    "ND": {
        "name": "North Dakota",
        "sos_business_filings_url": "https://sos.nd.gov/business",
        "business_name_search_url": "https://firststop.sos.nd.gov/search",
        "articles_of_organization_url": "https://sos.nd.gov/business/business-services",
        "annual_report_url": "https://sos.nd.gov/business/business-services",
        "registered_agent_info_url": "https://sos.nd.gov/business",
        "filing_fee_articles": "$135",
        "annual_fee_approximate": "$50 annual report",
        "notes": "Annual report due November 15.",
    },
    "OH": {
        "name": "Ohio",
        "sos_business_filings_url": "https://www.ohiosos.gov/businesses/",
        "business_name_search_url": "https://businesssearch.ohiosos.gov/",
        "articles_of_organization_url": "https://www.ohiosos.gov/businesses/filing-forms--fee-schedule/",
        "annual_report_url": "https://www.ohiosos.gov/businesses/",
        "registered_agent_info_url": "https://www.ohiosos.gov/businesses/",
        "filing_fee_articles": "$99",
        "annual_fee_approximate": "$0 (no annual report)",
        "notes": "Ohio is one of the very few states with NO annual report or franchise tax for LLCs.",
    },
    "OK": {
        "name": "Oklahoma",
        "sos_business_filings_url": "https://www.sos.ok.gov/business/default.aspx",
        "business_name_search_url": "https://www.sos.ok.gov/corp/corpInquiryFind.aspx",
        "articles_of_organization_url": "https://www.sos.ok.gov/business/forms.aspx",
        "annual_report_url": "https://www.sos.ok.gov/business/default.aspx",
        "registered_agent_info_url": "https://www.sos.ok.gov/business/default.aspx",
        "filing_fee_articles": "$100",
        "annual_fee_approximate": "$25 annual certificate",
        "notes": "Annual certificate due on formation anniversary.",
    },
    "OR": {
        "name": "Oregon",
        "sos_business_filings_url": "https://sos.oregon.gov/business/Pages/default.aspx",
        "business_name_search_url": "https://sos.oregon.gov/business/Pages/find.aspx",
        "articles_of_organization_url": "https://sos.oregon.gov/business/Pages/register.aspx",
        "annual_report_url": "https://sos.oregon.gov/business/Pages/renew.aspx",
        "registered_agent_info_url": "https://sos.oregon.gov/business/Pages/register-business-faq.aspx#registered-agent",
        "filing_fee_articles": "$100",
        "annual_fee_approximate": "$100 annual report",
        "notes": "Annual renewal due on formation anniversary.",
    },
    "PA": {
        "name": "Pennsylvania",
        "sos_business_filings_url": "https://www.dos.pa.gov/BusinessCharities/Business/Pages/default.aspx",
        "business_name_search_url": "https://www.corporations.pa.gov/search/corpsearch",
        "articles_of_organization_url": "https://www.dos.pa.gov/BusinessCharities/Business/Resources/Pages/default.aspx",
        "annual_report_url": "https://www.dos.pa.gov/BusinessCharities/Business/Resources/Pages/Annual-Report.aspx",
        "registered_agent_info_url": "https://www.dos.pa.gov/BusinessCharities/Business/Pages/default.aspx",
        "filing_fee_articles": "$125",
        "annual_fee_approximate": "$7 annual report (new requirement starting 2025; previously decennial)",
        "notes": "Pennsylvania switched from decennial to annual reports in 2025 — confirm current schedule on the DOS site.",
    },
    "RI": {
        "name": "Rhode Island",
        "sos_business_filings_url": "https://www.sos.ri.gov/divisions/business-services",
        "business_name_search_url": "https://business.sos.ri.gov/CorpWeb/CorpSearch/CorpSearch.aspx",
        "articles_of_organization_url": "https://www.sos.ri.gov/divisions/business-services/starting-a-business",
        "annual_report_url": "https://www.sos.ri.gov/divisions/business-services/annual-reports",
        "registered_agent_info_url": "https://www.sos.ri.gov/divisions/business-services",
        "filing_fee_articles": "$150",
        "annual_fee_approximate": "$50 annual report",
        "notes": "Annual report due between February 1 and May 1.",
    },
    "SC": {
        "name": "South Carolina",
        "sos_business_filings_url": "https://sos.sc.gov/online-filings/business-entities",
        "business_name_search_url": "https://businessfilings.sc.gov/BusinessFiling/Entity/Search",
        "articles_of_organization_url": "https://sos.sc.gov/online-filings/business-entities/forms-and-fees",
        "annual_report_url": "https://dor.sc.gov/tax/corporate",
        "registered_agent_info_url": "https://sos.sc.gov/online-filings/business-entities",
        "filing_fee_articles": "$110",
        "annual_fee_approximate": "$0 for LLCs (no annual report); corporations pay through Dept of Revenue",
        "notes": "South Carolina LLCs do NOT file annual reports. Corporations file through the SC Department of Revenue, not the SoS.",
    },
    "SD": {
        "name": "South Dakota",
        "sos_business_filings_url": "https://sosenterprise.sd.gov/BusinessServices/Business/RegistrationInstr.aspx",
        "business_name_search_url": "https://sosenterprise.sd.gov/BusinessServices/Business/FilingSearch.aspx",
        "articles_of_organization_url": "https://sosenterprise.sd.gov/BusinessServices/Business/RegistrationInstr.aspx",
        "annual_report_url": "https://sosenterprise.sd.gov/BusinessServices/Business/AnnualReportInstr.aspx",
        "registered_agent_info_url": "https://sosenterprise.sd.gov/BusinessServices/Business/RegistrationInstr.aspx",
        "filing_fee_articles": "$150",
        "annual_fee_approximate": "$50 annual report",
        "notes": "South Dakota has no state income tax. Annual report due on formation anniversary month.",
    },
    "TN": {
        "name": "Tennessee",
        "sos_business_filings_url": "https://sos.tn.gov/businesses",
        "business_name_search_url": "https://tnbear.tn.gov/Ecommerce/FilingSearch.aspx",
        "articles_of_organization_url": "https://sos.tn.gov/businesses/forms-fees-summary",
        "annual_report_url": "https://sos.tn.gov/businesses/annual-reports",
        "registered_agent_info_url": "https://sos.tn.gov/businesses",
        "filing_fee_articles": "$300 minimum ($50/member, min 6 / max 6,000)",
        "annual_fee_approximate": "$300 minimum annual report",
        "notes": "Tennessee LLC fees scale with member count ($50/member, $300 min, $3,000 max) — unusual structure. Also imposes franchise + excise taxes.",
    },
    "TX": {
        "name": "Texas",
        "sos_business_filings_url": "https://www.sos.state.tx.us/corp/index.shtml",
        "business_name_search_url": "https://direct.sos.state.tx.us/acct/acct-login.asp",
        "articles_of_organization_url": "https://www.sos.state.tx.us/corp/forms_boc.shtml",
        "annual_report_url": "https://comptroller.texas.gov/taxes/franchise/",
        "registered_agent_info_url": "https://www.sos.state.tx.us/corp/registeredagent.shtml",
        "filing_fee_articles": "$300",
        "annual_fee_approximate": "$0 (no annual report; franchise tax filing only — most small entities owe $0 below the $2.47M revenue threshold)",
        "notes": "Texas uses 'Certificate of Formation' instead of 'Articles of Organization'. No state income tax. Business name search is via SOSDirect (requires account). Franchise tax due May 15 annually; most small businesses owe $0 under the No Tax Due threshold but still must file.",
    },
    "UT": {
        "name": "Utah",
        "sos_business_filings_url": "https://corporations.utah.gov/",
        "business_name_search_url": "https://businesssearch.utah.gov/",
        "articles_of_organization_url": "https://corporations.utah.gov/business/registration/",
        "annual_report_url": "https://corporations.utah.gov/business/renewals/",
        "registered_agent_info_url": "https://corporations.utah.gov/business/registered-agent/",
        "filing_fee_articles": "$54 (online)",
        "annual_fee_approximate": "$18 annual renewal",
        "notes": "Filed through the Division of Corporations and Commercial Code. One of the cheapest states.",
    },
    "VT": {
        "name": "Vermont",
        "sos_business_filings_url": "https://sos.vermont.gov/corporations/",
        "business_name_search_url": "https://www.vtsosonline.com/online/BusinessInquire",
        "articles_of_organization_url": "https://sos.vermont.gov/corporations/registration/llc/",
        "annual_report_url": "https://sos.vermont.gov/corporations/other-services/annual-reports/",
        "registered_agent_info_url": "https://sos.vermont.gov/corporations/",
        "filing_fee_articles": "$125",
        "annual_fee_approximate": "$35 annual report (LLC) / $45 (Corp)",
        "notes": "Annual report due within 3 months of fiscal year end.",
    },
    "VA": {
        "name": "Virginia",
        "sos_business_filings_url": "https://www.scc.virginia.gov/pages/Business",
        "business_name_search_url": "https://cis.scc.virginia.gov/EntitySearch/Index",
        "articles_of_organization_url": "https://cis.scc.virginia.gov/",
        "annual_report_url": "https://www.scc.virginia.gov/pages/Annual-Registration-Fees",
        "registered_agent_info_url": "https://www.scc.virginia.gov/pages/Business",
        "filing_fee_articles": "$100",
        "annual_fee_approximate": "$50 annual registration fee (LLC) / $100 minimum (Corp)",
        "notes": "Virginia filings go through the State Corporation Commission (SCC), not the Secretary of State.",
    },
    "WA": {
        "name": "Washington",
        "sos_business_filings_url": "https://www.sos.wa.gov/corporations-charities/business-services",
        "business_name_search_url": "https://ccfs.sos.wa.gov/#/",
        "articles_of_organization_url": "https://www.sos.wa.gov/corporations-charities/business-services/start-business",
        "annual_report_url": "https://www.sos.wa.gov/corporations-charities/business-services/annual-reports",
        "registered_agent_info_url": "https://www.sos.wa.gov/corporations-charities/business-services",
        "filing_fee_articles": "$200 (online)",
        "annual_fee_approximate": "$70 annual report",
        "notes": "Washington has no state income tax but does impose B&O (Business and Occupation) tax on gross receipts.",
    },
    "WV": {
        "name": "West Virginia",
        "sos_business_filings_url": "https://sos.wv.gov/business/Pages/default.aspx",
        "business_name_search_url": "https://apps.sos.wv.gov/business/corporations/",
        "articles_of_organization_url": "https://business4.wv.gov/Pages/default.aspx",
        "annual_report_url": "https://sos.wv.gov/business/Pages/AnnualReport.aspx",
        "registered_agent_info_url": "https://sos.wv.gov/business/Pages/default.aspx",
        "filing_fee_articles": "$100",
        "annual_fee_approximate": "$25 annual report",
        "notes": "Annual report due July 1.",
    },
    "WI": {
        "name": "Wisconsin",
        "sos_business_filings_url": "https://www.wdfi.org/corporations/",
        "business_name_search_url": "https://www.wdfi.org/apps/corpsearch/search.aspx",
        "articles_of_organization_url": "https://www.wdfi.org/corporations/forms/",
        "annual_report_url": "https://www.wdfi.org/corporations/annual_report/",
        "registered_agent_info_url": "https://www.wdfi.org/corporations/",
        "filing_fee_articles": "$130 (online) / $170 (paper)",
        "annual_fee_approximate": "$25 annual report",
        "notes": "Wisconsin files through the Department of Financial Institutions (DFI), not the SoS.",
    },
    "WY": {
        "name": "Wyoming",
        "sos_business_filings_url": "https://sos.wyo.gov/Business/Default.aspx",
        "business_name_search_url": "https://wyobiz.wyo.gov/Business/FilingSearch.aspx",
        "articles_of_organization_url": "https://sos.wyo.gov/Business/StartABusiness.aspx",
        "annual_report_url": "https://sos.wyo.gov/Business/AnnualReport.aspx",
        "registered_agent_info_url": "https://sos.wyo.gov/Business/RegisteredAgent.aspx",
        "filing_fee_articles": "$100",
        "annual_fee_approximate": "$60 minimum annual report (varies with in-state assets)",
        "notes": "Wyoming is the original asset-protection LLC state — strong charging order protection, no state income tax, and series LLC support. Popular for holding companies and asset-protection structures. As with Delaware, if you operate in another state you'll need foreign-LLC registration there.",
    },
    "DC": {
        "name": "District of Columbia",
        "sos_business_filings_url": "https://dlcp.dc.gov/page/corporations-division",
        "business_name_search_url": "https://corponline.dcra.dc.gov/Home.aspx",
        "articles_of_organization_url": "https://dlcp.dc.gov/page/corporations-division",
        "annual_report_url": "https://dlcp.dc.gov/page/biennial-reports",
        "registered_agent_info_url": "https://dlcp.dc.gov/page/corporations-division",
        "filing_fee_articles": "$99 (LLC) / $99 (Corp)",
        "annual_fee_approximate": "$300 biennial report",
        "notes": "DC files through the Department of Licensing and Consumer Protection (DLCP), Corporations Division. Biennial — not annual — but the fee ($300) is high.",
    },
}


FEDERAL_PORTALS: dict[str, str] = {
    # Apply for an EIN (Employer Identification Number) from the IRS — free.
    "ein_application": "https://www.irs.gov/businesses/small-businesses-self-employed/apply-for-an-employer-identification-number-ein-online",
    # Beneficial Ownership Information report (FinCEN, post-Corporate Transparency Act).
    "boi_filing": "https://boiefiling.fincen.gov/",
    # FinCEN BOI FAQ / explainer for founders.
    "boi_faq": "https://www.fincen.gov/boi-faqs",
    # SBA local assistance — find your nearest SBDC / SCORE / Women's Business Center.
    "sba_local_assistance": "https://www.sba.gov/local-assistance",
    # SBA business structure overview (entity-type comparison).
    "sba_business_structures": "https://www.sba.gov/business-guide/launch-your-business/choose-business-structure",
    # IRS small-business / self-employed hub — tax election guidance.
    "irs_small_business": "https://www.irs.gov/businesses/small-businesses-self-employed",
    # IRS Form 2553 (S-Corp election).
    "irs_form_2553": "https://www.irs.gov/forms-pubs/about-form-2553",
    # IRS Form 8832 (entity classification election).
    "irs_form_8832": "https://www.irs.gov/forms-pubs/about-form-8832",
    # USPTO trademark search (TESS) — check name conflicts beyond your state.
    "uspto_tess": "https://tmsearch.uspto.gov/search/search-information",
    # USPTO trademark application portal.
    "uspto_teas": "https://www.uspto.gov/trademarks/apply",
}


def get_state(state: str) -> dict[str, str | None] | None:
    """Look up a state's portal dict by 2-letter code OR full name.

    Args:
        state: "TX", "tx", "Texas", "texas" all work.

    Returns:
        The portal dict, or None if no match.
    """
    if not state:
        return None
    key = state.strip().upper()
    if key in STATE_PORTALS:
        return STATE_PORTALS[key]
    # Try full-name lookup (case-insensitive).
    lower = state.strip().lower()
    for code, data in STATE_PORTALS.items():
        if data.get("name", "").lower() == lower:
            return data | {"_code": code}
    return None
